// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    recipes,
    recipeVariants,
    recipeSteps,
    ingredientItems,
    nutrients,
    conversions,
    metadata,
    recipeVariantsRecipeId,
    recipeStepsRecipeId,
    recipeStepsVariantId,
    ingredientItemsStepId,
    ingredientItemsLowerName,
    conversionsFoodMeasure,
  ];
  late final Shape0 recipes = Shape0(
    source: i0.VersionedTable(
      entityName: 'recipes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 recipeVariants = Shape1(
    source: i0.VersionedTable(
      entityName: 'recipe_variants',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_29, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 recipeSteps = Shape2(
    source: i0.VersionedTable(
      entityName: 'recipe_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((recipe_id IS NULL)<>(variant_id IS NULL))'],
      columns: [
        _column_0,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_3,
        _column_25,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ingredientItems = Shape3(
    source: i0.VersionedTable(
      entityName: 'ingredient_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_36,
        _column_37,
        _column_32,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 nutrients = Shape4(
    source: i0.VersionedTable(
      entityName: 'nutrients',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 conversions = Shape5(
    source: i0.VersionedTable(
      entityName: 'conversions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_42,
        _column_94,
        _column_46,
        _column_47,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 metadata = Shape6(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_96, _column_97],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index recipeVariantsRecipeId = i1.Index(
    'recipe_variants_recipe_id',
    'CREATE INDEX recipe_variants_recipe_id ON recipe_variants (recipe_id)',
  );
  final i1.Index recipeStepsRecipeId = i1.Index(
    'recipe_steps_recipe_id',
    'CREATE INDEX recipe_steps_recipe_id ON recipe_steps (recipe_id)',
  );
  final i1.Index recipeStepsVariantId = i1.Index(
    'recipe_steps_variant_id',
    'CREATE INDEX recipe_steps_variant_id ON recipe_steps (variant_id)',
  );
  final i1.Index ingredientItemsStepId = i1.Index(
    'ingredient_items_step_id',
    'CREATE INDEX ingredient_items_step_id ON ingredient_items (step_id)',
  );
  final i1.Index ingredientItemsLowerName = i1.Index(
    'ingredient_items_lower_name',
    'CREATE INDEX ingredient_items_lower_name ON ingredient_items (lower_name, shape)',
  );
  final i1.Index conversionsFoodMeasure = i1.Index(
    'conversions_food_measure',
    'CREATE UNIQUE INDEX conversions_food_measure ON conversions (food_id, measure_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imagePath =>
      columnsByName['image_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get servings =>
      columnsByName['servings']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get piecesPerServing =>
      columnsByName['pieces_per_serving']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get category =>
      columnsByName['category']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get countryCode =>
      columnsByName['country_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get calories =>
      columnsByName['calories']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fat =>
      columnsByName['fat']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get carbohydrates =>
      columnsByName['carbohydrates']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get saturatedFat =>
      columnsByName['saturated_fat']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get transFat =>
      columnsByName['trans_fat']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sugar =>
      columnsByName['sugar']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fiber =>
      columnsByName['fiber']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cholesterol =>
      columnsByName['cholesterol']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sodium =>
      columnsByName['sodium']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get time =>
      columnsByName['time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cookTime =>
      columnsByName['cook_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get prepTime =>
      columnsByName['prep_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restTime =>
      columnsByName['rest_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get month =>
      columnsByName['month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get makeAhead =>
      columnsByName['make_ahead']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get questions =>
      columnsByName['questions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get languageTag =>
      columnsByName['language_tag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get favorite =>
      columnsByName['favorite']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'servings',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pieces_per_serving',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'country_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'calories',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'carbohydrates',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'protein',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'saturated_fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'trans_fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sugar',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fiber',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cholesterol',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sodium',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cook_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'prep_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'month',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'make_ahead',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'video_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'questions',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language_tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'favorite',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (favorite IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recipeId =>
      columnsByName['recipe_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recipe_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES recipes(id)ON DELETE CASCADE',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recipeId =>
      columnsByName['recipe_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get variantId =>
      columnsByName['variant_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instruction =>
      columnsByName['instruction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imagePath =>
      columnsByName['image_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timer =>
      columnsByName['timer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stepOrder =>
      columnsByName['step_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recipe_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES recipes(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'variant_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES recipe_variants(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'instruction',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'timer',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'step_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stepId =>
      columnsByName['step_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lowerName =>
      columnsByName['lower_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get unit =>
      columnsByName['unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get shape =>
      columnsByName['shape']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get conversionId =>
      columnsByName['conversion_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get optional =>
      columnsByName['optional']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'step_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES recipe_steps(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lower_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_40(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'shape',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'food_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'conversion_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'optional',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (optional IN (0, 1))',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get descEn =>
      columnsByName['desc_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descFr =>
      columnsByName['desc_fr']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get water =>
      columnsByName['water']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lipidTotal =>
      columnsByName['lipid_total']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get energKcal =>
      columnsByName['energ_kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbohydrates =>
      columnsByName['carbohydrates']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ash =>
      columnsByName['ash']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fiber =>
      columnsByName['fiber']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sugar =>
      columnsByName['sugar']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get calcium =>
      columnsByName['calcium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get iron =>
      columnsByName['iron']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get magnesium =>
      columnsByName['magnesium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get phosphorus =>
      columnsByName['phosphorus']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get potassium =>
      columnsByName['potassium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sodium =>
      columnsByName['sodium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get zinc =>
      columnsByName['zinc']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get copper =>
      columnsByName['copper']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get manganese =>
      columnsByName['manganese']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get selenium =>
      columnsByName['selenium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminC =>
      columnsByName['vitamin_c']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get thiamin =>
      columnsByName['thiamin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get riboflavin =>
      columnsByName['riboflavin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get niacin =>
      columnsByName['niacin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get pantoAcid =>
      columnsByName['panto_acid']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminB6 =>
      columnsByName['vitamin_b6']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get folateTotal =>
      columnsByName['folate_total']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get folicAcid =>
      columnsByName['folic_acid']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get foodFolate =>
      columnsByName['food_folate']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get folateDfe =>
      columnsByName['folate_dfe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cholineTotal =>
      columnsByName['choline_total']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminB12 =>
      columnsByName['vitamin_b12']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminAIu =>
      columnsByName['vitamin_a_iu']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminARae =>
      columnsByName['vitamin_a_rae']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get retinol =>
      columnsByName['retinol']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get alphaCarot =>
      columnsByName['alpha_carot']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get betaCarot =>
      columnsByName['beta_carot']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get betaCrypt =>
      columnsByName['beta_crypt']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lycopene =>
      columnsByName['lycopene']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lutZea =>
      columnsByName['lut_zea']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminE =>
      columnsByName['vitamin_e']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminD =>
      columnsByName['vitamin_d']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminDIu =>
      columnsByName['vitamin_d_iu']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminK =>
      columnsByName['vitamin_k']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get faSat =>
      columnsByName['fa_sat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get faMono =>
      columnsByName['fa_mono']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get faPoly =>
      columnsByName['fa_poly']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cholesterol =>
      columnsByName['cholesterol']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'food_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'desc_en',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'desc_fr',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_48(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_49(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'water',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_50(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lipid_total',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_51(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'energ_kcal',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_52(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbohydrates',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_53(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ash',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_54(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fiber',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_55(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sugar',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'calcium',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_57(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'iron',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_58(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'magnesium',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_59(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'phosphorus',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_60(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'potassium',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_61(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sodium',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_62(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'zinc',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_63(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'copper',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_64(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'manganese',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_65(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'selenium',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_66(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_c',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_67(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'thiamin',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_68(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'riboflavin',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_69(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'niacin',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_70(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'panto_acid',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_71(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_b6',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_72(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'folate_total',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_73(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'folic_acid',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_74(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'food_folate',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_75(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'folate_dfe',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_76(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'choline_total',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_77(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_b12',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_78(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_a_iu',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_79(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_a_rae',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_80(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'retinol',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_81(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'alpha_carot',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_82(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'beta_carot',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_83(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'beta_crypt',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_84(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lycopene',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_85(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lut_zea',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_86(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_e',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_87(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_d',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_88(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_d_iu',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_89(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'vitamin_k',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_90(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fa_sat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_91(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fa_mono',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_92(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fa_poly',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_93(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'cholesterol',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get measureId =>
      columnsByName['measure_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get descEn =>
      columnsByName['desc_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descFr =>
      columnsByName['desc_fr']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get factor =>
      columnsByName['factor']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_94(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'measure_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_95(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'factor',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_96(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_97(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    recipes,
    recipeVariants,
    recipeSteps,
    ingredientItems,
    nutrients,
    conversions,
    metadata,
    recipeVariantsRecipeId,
    recipeStepsRecipeId,
    recipeStepsVariantId,
    ingredientItemsStepId,
    ingredientItemsLowerName,
    conversionsFoodMeasure,
  ];
  late final Shape0 recipes = Shape0(
    source: i0.VersionedTable(
      entityName: 'recipes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 recipeVariants = Shape1(
    source: i0.VersionedTable(
      entityName: 'recipe_variants',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_29, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 recipeSteps = Shape2(
    source: i0.VersionedTable(
      entityName: 'recipe_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((recipe_id IS NULL)<>(variant_id IS NULL))'],
      columns: [
        _column_0,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_3,
        _column_25,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 ingredientItems = Shape7(
    source: i0.VersionedTable(
      entityName: 'ingredient_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_36,
        _column_37,
        _column_32,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_98,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 nutrients = Shape4(
    source: i0.VersionedTable(
      entityName: 'nutrients',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 conversions = Shape5(
    source: i0.VersionedTable(
      entityName: 'conversions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_42,
        _column_94,
        _column_46,
        _column_47,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 metadata = Shape6(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_96, _column_97],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index recipeVariantsRecipeId = i1.Index(
    'recipe_variants_recipe_id',
    'CREATE INDEX recipe_variants_recipe_id ON recipe_variants (recipe_id)',
  );
  final i1.Index recipeStepsRecipeId = i1.Index(
    'recipe_steps_recipe_id',
    'CREATE INDEX recipe_steps_recipe_id ON recipe_steps (recipe_id)',
  );
  final i1.Index recipeStepsVariantId = i1.Index(
    'recipe_steps_variant_id',
    'CREATE INDEX recipe_steps_variant_id ON recipe_steps (variant_id)',
  );
  final i1.Index ingredientItemsStepId = i1.Index(
    'ingredient_items_step_id',
    'CREATE INDEX ingredient_items_step_id ON ingredient_items (step_id)',
  );
  final i1.Index ingredientItemsLowerName = i1.Index(
    'ingredient_items_lower_name',
    'CREATE INDEX ingredient_items_lower_name ON ingredient_items (lower_name, shape)',
  );
  final i1.Index conversionsFoodMeasure = i1.Index(
    'conversions_food_measure',
    'CREATE UNIQUE INDEX conversions_food_measure ON conversions (food_id, measure_id)',
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stepId =>
      columnsByName['step_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lowerName =>
      columnsByName['lower_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get unit =>
      columnsByName['unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get shape =>
      columnsByName['shape']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get conversionId =>
      columnsByName['conversion_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get optional =>
      columnsByName['optional']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get originalMeasure =>
      columnsByName['original_measure']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_98(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_measure',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    recipes,
    recipeVariants,
    recipeSteps,
    ingredientItems,
    nutrients,
    conversions,
    metadata,
    recipeVariantsRecipeId,
    recipeStepsRecipeId,
    recipeStepsVariantId,
    ingredientItemsStepId,
    ingredientItemsLowerName,
    conversionsFoodMeasure,
  ];
  late final Shape0 recipes = Shape0(
    source: i0.VersionedTable(
      entityName: 'recipes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recipeVariants = Shape8(
    source: i0.VersionedTable(
      entityName: 'recipe_variants',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_29, _column_1, _column_99],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 recipeSteps = Shape2(
    source: i0.VersionedTable(
      entityName: 'recipe_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((recipe_id IS NULL)<>(variant_id IS NULL))'],
      columns: [
        _column_0,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_3,
        _column_25,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 ingredientItems = Shape7(
    source: i0.VersionedTable(
      entityName: 'ingredient_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_36,
        _column_37,
        _column_32,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_98,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 nutrients = Shape4(
    source: i0.VersionedTable(
      entityName: 'nutrients',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 conversions = Shape5(
    source: i0.VersionedTable(
      entityName: 'conversions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_42,
        _column_94,
        _column_46,
        _column_47,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 metadata = Shape6(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_96, _column_97],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index recipeVariantsRecipeId = i1.Index(
    'recipe_variants_recipe_id',
    'CREATE INDEX recipe_variants_recipe_id ON recipe_variants (recipe_id)',
  );
  final i1.Index recipeStepsRecipeId = i1.Index(
    'recipe_steps_recipe_id',
    'CREATE INDEX recipe_steps_recipe_id ON recipe_steps (recipe_id)',
  );
  final i1.Index recipeStepsVariantId = i1.Index(
    'recipe_steps_variant_id',
    'CREATE INDEX recipe_steps_variant_id ON recipe_steps (variant_id)',
  );
  final i1.Index ingredientItemsStepId = i1.Index(
    'ingredient_items_step_id',
    'CREATE INDEX ingredient_items_step_id ON ingredient_items (step_id)',
  );
  final i1.Index ingredientItemsLowerName = i1.Index(
    'ingredient_items_lower_name',
    'CREATE INDEX ingredient_items_lower_name ON ingredient_items (lower_name, shape)',
  );
  final i1.Index conversionsFoodMeasure = i1.Index(
    'conversions_food_measure',
    'CREATE UNIQUE INDEX conversions_food_measure ON conversions (food_id, measure_id)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recipeId =>
      columnsByName['recipe_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imagePath =>
      columnsByName['image_path']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_99(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    recipes,
    recipeVariants,
    recipeSteps,
    ingredientItems,
    nutrients,
    conversions,
    metadata,
    recipeVariantsRecipeId,
    recipeStepsRecipeId,
    recipeStepsVariantId,
    ingredientItemsStepId,
    ingredientItemsLowerName,
    conversionsFoodMeasure,
  ];
  late final Shape0 recipes = Shape0(
    source: i0.VersionedTable(
      entityName: 'recipes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recipeVariants = Shape8(
    source: i0.VersionedTable(
      entityName: 'recipe_variants',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_29, _column_1, _column_99],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 recipeSteps = Shape9(
    source: i0.VersionedTable(
      entityName: 'recipe_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((recipe_id IS NULL)<>(variant_id IS NULL))'],
      columns: [
        _column_0,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_3,
        _column_25,
        _column_34,
        _column_35,
        _column_100,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 ingredientItems = Shape7(
    source: i0.VersionedTable(
      entityName: 'ingredient_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_36,
        _column_37,
        _column_32,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_98,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 nutrients = Shape4(
    source: i0.VersionedTable(
      entityName: 'nutrients',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 conversions = Shape5(
    source: i0.VersionedTable(
      entityName: 'conversions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_42,
        _column_94,
        _column_46,
        _column_47,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 metadata = Shape6(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_96, _column_97],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index recipeVariantsRecipeId = i1.Index(
    'recipe_variants_recipe_id',
    'CREATE INDEX recipe_variants_recipe_id ON recipe_variants (recipe_id)',
  );
  final i1.Index recipeStepsRecipeId = i1.Index(
    'recipe_steps_recipe_id',
    'CREATE INDEX recipe_steps_recipe_id ON recipe_steps (recipe_id)',
  );
  final i1.Index recipeStepsVariantId = i1.Index(
    'recipe_steps_variant_id',
    'CREATE INDEX recipe_steps_variant_id ON recipe_steps (variant_id)',
  );
  final i1.Index ingredientItemsStepId = i1.Index(
    'ingredient_items_step_id',
    'CREATE INDEX ingredient_items_step_id ON ingredient_items (step_id)',
  );
  final i1.Index ingredientItemsLowerName = i1.Index(
    'ingredient_items_lower_name',
    'CREATE INDEX ingredient_items_lower_name ON ingredient_items (lower_name, shape)',
  );
  final i1.Index conversionsFoodMeasure = i1.Index(
    'conversions_food_measure',
    'CREATE UNIQUE INDEX conversions_food_measure ON conversions (food_id, measure_id)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recipeId =>
      columnsByName['recipe_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get variantId =>
      columnsByName['variant_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instruction =>
      columnsByName['instruction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imagePath =>
      columnsByName['image_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timer =>
      columnsByName['timer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stepOrder =>
      columnsByName['step_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get linkedRecipeId =>
      columnsByName['linked_recipe_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_100(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'linked_recipe_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES recipes(id)ON DELETE SET NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    recipes,
    recipeVariants,
    recipeSteps,
    ingredientItems,
    nutrients,
    conversions,
    metadata,
    recipeVariantsRecipeId,
    recipeStepsRecipeId,
    recipeStepsVariantId,
    ingredientItemsStepId,
    ingredientItemsLowerName,
    conversionsFoodMeasure,
  ];
  late final Shape0 recipes = Shape0(
    source: i0.VersionedTable(
      entityName: 'recipes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 recipeVariants = Shape8(
    source: i0.VersionedTable(
      entityName: 'recipe_variants',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_29, _column_1, _column_99],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 recipeSteps = Shape9(
    source: i0.VersionedTable(
      entityName: 'recipe_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((recipe_id IS NULL)<>(variant_id IS NULL))'],
      columns: [
        _column_0,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_3,
        _column_25,
        _column_34,
        _column_35,
        _column_100,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 ingredientItems = Shape7(
    source: i0.VersionedTable(
      entityName: 'ingredient_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_36,
        _column_37,
        _column_32,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_98,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 nutrients = Shape10(
    source: i0.VersionedTable(
      entityName: 'nutrients',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_101,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 conversions = Shape5(
    source: i0.VersionedTable(
      entityName: 'conversions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_42,
        _column_94,
        _column_46,
        _column_47,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 metadata = Shape6(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_96, _column_97],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index recipeVariantsRecipeId = i1.Index(
    'recipe_variants_recipe_id',
    'CREATE INDEX recipe_variants_recipe_id ON recipe_variants (recipe_id)',
  );
  final i1.Index recipeStepsRecipeId = i1.Index(
    'recipe_steps_recipe_id',
    'CREATE INDEX recipe_steps_recipe_id ON recipe_steps (recipe_id)',
  );
  final i1.Index recipeStepsVariantId = i1.Index(
    'recipe_steps_variant_id',
    'CREATE INDEX recipe_steps_variant_id ON recipe_steps (variant_id)',
  );
  final i1.Index ingredientItemsStepId = i1.Index(
    'ingredient_items_step_id',
    'CREATE INDEX ingredient_items_step_id ON ingredient_items (step_id)',
  );
  final i1.Index ingredientItemsLowerName = i1.Index(
    'ingredient_items_lower_name',
    'CREATE INDEX ingredient_items_lower_name ON ingredient_items (lower_name, shape)',
  );
  final i1.Index conversionsFoodMeasure = i1.Index(
    'conversions_food_measure',
    'CREATE UNIQUE INDEX conversions_food_measure ON conversions (food_id, measure_id)',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get descEn =>
      columnsByName['desc_en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descFr =>
      columnsByName['desc_fr']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get water =>
      columnsByName['water']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lipidTotal =>
      columnsByName['lipid_total']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get energKcal =>
      columnsByName['energ_kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbohydrates =>
      columnsByName['carbohydrates']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ash =>
      columnsByName['ash']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fiber =>
      columnsByName['fiber']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sugar =>
      columnsByName['sugar']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get calcium =>
      columnsByName['calcium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get iron =>
      columnsByName['iron']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get magnesium =>
      columnsByName['magnesium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get phosphorus =>
      columnsByName['phosphorus']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get potassium =>
      columnsByName['potassium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sodium =>
      columnsByName['sodium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get zinc =>
      columnsByName['zinc']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get copper =>
      columnsByName['copper']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get manganese =>
      columnsByName['manganese']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get selenium =>
      columnsByName['selenium']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminC =>
      columnsByName['vitamin_c']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get thiamin =>
      columnsByName['thiamin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get riboflavin =>
      columnsByName['riboflavin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get niacin =>
      columnsByName['niacin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get pantoAcid =>
      columnsByName['panto_acid']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminB6 =>
      columnsByName['vitamin_b6']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get folateTotal =>
      columnsByName['folate_total']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get folicAcid =>
      columnsByName['folic_acid']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get foodFolate =>
      columnsByName['food_folate']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get folateDfe =>
      columnsByName['folate_dfe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cholineTotal =>
      columnsByName['choline_total']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminB12 =>
      columnsByName['vitamin_b12']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminAIu =>
      columnsByName['vitamin_a_iu']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminARae =>
      columnsByName['vitamin_a_rae']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get retinol =>
      columnsByName['retinol']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get alphaCarot =>
      columnsByName['alpha_carot']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get betaCarot =>
      columnsByName['beta_carot']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get betaCrypt =>
      columnsByName['beta_crypt']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lycopene =>
      columnsByName['lycopene']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lutZea =>
      columnsByName['lut_zea']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminE =>
      columnsByName['vitamin_e']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminD =>
      columnsByName['vitamin_d']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminDIu =>
      columnsByName['vitamin_d_iu']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get vitaminK =>
      columnsByName['vitamin_k']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get faSat =>
      columnsByName['fa_sat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get faMono =>
      columnsByName['fa_mono']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get faPoly =>
      columnsByName['fa_poly']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cholesterol =>
      columnsByName['cholesterol']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get foodGroup =>
      columnsByName['food_group']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_101(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'food_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
